export const vaktChangeRequestsConstants = {
    START_GET_ALLVAKTCHANGEREQUESTS: 'START_GET_ALLVAKTCHANGEREQUESTS',
    GET_ALLVAKTCHANGEREQUESTS_SUCCEEDED: 'GET_ALLVAKTCHANGEREQUESTS_SUCCEEDED',
    GET_ALLVAKTCHANGEREQUESTS_FAILED: 'GET_ALLVAKTCHANGEREQUESTS_FAILED',

    START_GET_VAKTCHANGEREQUESTS: 'START_GET_VAKTCHANGEREQUESTS',
    GET_VAKTCHANGEREQUESTS_SUCCEEDED: 'GET_VAKTCHANGEREQUESTS_SUCCEEDED',
    GET_VAKTCHANGEREQUESTS_FAILED: 'GET_VAKTCHANGEREQUESTS_FAILED',

    START_GET_VAKTCHANGEREQUESTSRECEIVED: 'START_GET_VAKTCHANGEREQUESTSRECEIVED',
    GET_VAKTCHANGEREQUESTSRECEIVED_SUCCEEDED: 'GET_VAKTCHANGEREQUESTSRECEIVED_SUCCEEDED',
    GET_VAKTCHANGEREQUESTSRECEIVED_FAILED: 'GET_VAKTCHANGEREQUESTSRECEIVED_FAILED',

    START_SAVE_VAKTCHANGEREQUESTS: 'START_SAVE_VAKTCHANGEREQUESTS',
    SAVE_VAKTCHANGEREQUESTS_SUCCEEDED: 'SAVE_VAKTCHANGEREQUESTS_SUCCEEDED',
    SAVE_VAKTCHANGEREQUESTS_FAILED: 'SAVE_VAKTCHANGEREQUESTS_FAILED',

    START_SAVE_VAKTCHANGESUGGESTIONS: 'START_SAVE_VAKTCHANGESUGGESTIONS',
    SAVE_VAKTCHANGESUGGESTIONS_SUCCEEDED: 'SAVE_VAKTCHANGESUGGESTIONS_SUCCEEDED',
    SAVE_VAKTCHANGESUGGESTIONS_FAILED: 'SAVE_VAKTCHANGESUGGESTIONS_FAILED',

    START_ACCEPTVAKTCHANGE: 'START_ACCEPTVAKTCHANGE',
    ACCEPTVAKTCHANGE_SUCCEEDED: 'ACCEPTVAKTCHANGE_SUCCEEDED',
    ACCEPTVAKTCHANGE_FAILED: 'ACCEPTVAKTCHANGE_FAILED',

    START_UNDOVAKTCHANGE: 'START_UNDOVAKTCHANGE',
    UNDOVAKTCHANGE_SUCCEEDED: 'UNDOVAKTCHANGE_SUCCEEDED',
    UNDOVAKTCHANGE_FAILED: 'UNDOVAKTCHANGE_FAILED'

};
