export const avdelingerConstants = {
    START_GET_AVDELINGER: 'START_GET_AVDELINGER',
    GET_AVDELINGER_SUCCEEDED: 'GET_AVDELINGER_SUCCEEDED',
    GET_AVDELINGER_FAILED: 'GET_AVDELINGER_FAILED',
    START_CREATE_AVDELING: 'START_CREATE_AVDELING',
    CREATE_AVDELING_SUCCEEDED: 'CREATE_AVDELING_SUCCEEDED',
    CREATE_AVDELING_FAILED: 'CREATE_AVDELING_FAILED',
    START_EDIT_AVDELING: 'START_EDIT_AVDELING',
    EDIT_AVDELING_SUCCEEDED: 'EDIT_AVDELING_SUCCEEDED',
    EDIT_AVDELING_FAILED: 'EDIT_AVDELING_FAILED',
    START_DELETE_AVDELING: 'START_DELETE_AVDELING',
    DELETE_AVDELING_SUCCEEDED: 'DELETE_AVDELING_SUCCEEDED',
    DELETE_AVDELING_FAILED: 'DELETE_AVDELING_FAILED',
};


export default avdelingerConstants;