export const tjenesteplanChangesConstants = {
    START_GET_TJENESTEPLANCHANGES: 'START_GET_TJENESTEPLANCHANGES',
    GET_TJENESTEPLANCHANGES_SUCCEEDED: 'GET_TJENESTEPLANCHANGES_SUCCEEDED',
    GET_TJENESTEPLANCHANGES_FAILED: 'GET_TJENESTEPLANCHANGES_FAILED'
};


export default tjenesteplanChangesConstants;