// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tjenesteplan.Data.Contexts;

namespace Tjenesteplan.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190501195513_AddVaktChangeRequestsTable")]
    partial class AddVaktChangeRequestsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tjenesteplan.Data.Features.Invitations.InvitationEntity", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.HasKey("Guid");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("NumberOfWeeks");

                    b.Property<DateTime>("StartDate");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tjenesteplaner");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanUkedagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dagsplan");

                    b.Property<DateTime>("Date");

                    b.Property<int>("TjenesteplanId");

                    b.Property<int>("TjenesteplanUkeId");

                    b.HasKey("Id");

                    b.HasIndex("TjenesteplanId", "TjenesteplanUkeId");

                    b.ToTable("TjenesteplanUkedager");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanUkeEntity", b =>
                {
                    b.Property<int>("TjenesteplanId");

                    b.Property<int>("TjenesteplanUkeId");

                    b.Property<int?>("UserId");

                    b.HasKey("TjenesteplanId", "TjenesteplanUkeId");

                    b.HasIndex("UserId");

                    b.ToTable("TjenesteplanUker");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.VaktChangeRequests.VaktChangeRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("RequestRegisteredDate");

                    b.Property<int>("Status");

                    b.Property<int>("TjenesteplanId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TjenesteplanId");

                    b.HasIndex("UserId");

                    b.ToTable("VaktChangeRequests");
                });

            modelBuilder.Entity("WebApi.Features.Users.Data.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<int>("Role");

                    b.Property<int?>("TjenesteplanId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("TjenesteplanId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanEntity", b =>
                {
                    b.HasOne("WebApi.Features.Users.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanUkedagEntity", b =>
                {
                    b.HasOne("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanUkeEntity", "TjenesteplanUke")
                        .WithMany("Days")
                        .HasForeignKey("TjenesteplanId", "TjenesteplanUkeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanUkeEntity", b =>
                {
                    b.HasOne("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanEntity", "Tjenesteplan")
                        .WithMany("Weeks")
                        .HasForeignKey("TjenesteplanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Features.Users.Data.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Tjenesteplan.Data.Features.VaktChangeRequests.VaktChangeRequestEntity", b =>
                {
                    b.HasOne("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanEntity", "Tjenesteplan")
                        .WithMany("VaktChangeRequests")
                        .HasForeignKey("TjenesteplanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApi.Features.Users.Data.UserEntity", "User")
                        .WithMany("VaktChangeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApi.Features.Users.Data.UserEntity", b =>
                {
                    b.HasOne("Tjenesteplan.Data.Features.Tjenesteplan.Data.TjenesteplanEntity", "Tjenesteplan")
                        .WithMany("Leger")
                        .HasForeignKey("TjenesteplanId");
                });
#pragma warning restore 612, 618
        }
    }
}
