export const dagsplanerConstants = {
    START_FETCH_DAGSPLANER: 'START_FETCH_DAGSPLANER',
    FETCH_DAGSPLANER_SUCCEEDED: 'FETCH_DAGSPLANER_SUCCEEDED',
    FETCH_DAGSPLANER_FAILED: 'FETCH_DAGSPLANER_FAILED'
};
