export const legeSpesialiteterConstants = {
    START_FETCH_LEGESPESIALITETER: 'START_FETCH_LEGESPESIALITETER',
    FETCH_LEGESPESIALITETER_SUCCEEDED: 'FETCH_LEGESPESIALITETER_SUCCEEDED',
    FETCH_LEGESPESIALITETER_FAILED: 'FETCH_LEGESPESIALITETER_FAILED'
};
