export const vakansvaktRequestsConstants = {
    START_GET_VAKANSVAKTREQUESTS: 'START_GET_VAKANSVAKTREQUESTS',
    GET_VAKANSVAKTREQUESTS_SUCCEEDED: 'GET_VAKANSVAKTREQUESTS_SUCCEEDED',
    GET_VAKANSVAKTREQUESTS_FAILED: 'GET_VAKANSVAKTREQUESTS_FAILED',

    START_GET_APPROVEDVAKANSVAKTREQUESTS: 'START_GET_APPROVEDVAKANSVAKTREQUESTS',
    GET_APPROVEDVAKANSVAKTREQUESTS_SUCCEEDED: 'GET_APPROVEDVAKANSVAKTREQUESTS_SUCCEEDED',
    GET_APPROVEDVAKANSVAKTREQUESTS_FAILED: 'GET_APPROVEDVAKANSVAKTREQUESTS_FAILED',

    START_GET_AVAILABLEVAKANSVAKTREQUESTS: 'START_GET_AVAILABLEVAKANSVAKTREQUESTS',
    GET_AVAILABLEVAKANSVAKTREQUESTS_SUCCEEDED: 'GET_AVAILABLEVAKANSVAKTREQUESTS_SUCCEEDED',
    GET_AVAILABLEVAKANSVAKTREQUESTS_FAILED: 'GET_AVAILABLEVAKANSVAKTREQUESTS_FAILED',

    START_GET_VAKANSVAKTREQUEST: 'START_GET_VAKANSVAKTREQUEST',
    GET_VAKANSVAKTREQUEST_SUCCEEDED: 'GET_VAKANSVAKTREQUEST_SUCCEEDED',
    GET_VAKANSVAKTREQUEST_FAILED: 'GET_VAKANSVAKTREQUEST_FAILED',

    START_APPROVEVAKANSVAKTREQUEST: 'START_APPROVEVAKANSVAKTREQUEST',
    APPROVEVAKANSVAKTREQUEST_SUCCEEDED: 'APPROVEVAKANSVAKTREQUEST_SUCCEEDED',
    APPROVEVAKANSVAKTREQUEST_FAILED: 'APPROVEVAKANSVAKTREQUEST_FAILED',

    START_REJECTVAKANSVAKTREQUEST: 'START_REJECTVAKANSVAKTREQUEST',
    REJECTVAKANSVAKTREQUEST_SUCCEEDED: 'REJECTVAKANSVAKTREQUEST_SUCCEEDED',
    REJECTVAKANSVAKTREQUEST_FAILED: 'REJECTVAKANSVAKTREQUEST_FAILED',

    START_ACCEPTVAKANSVAKTREQUEST: 'START_ACCEPTVAKANSVAKTREQUEST',
    ACCEPTVAKANSVAKTREQUEST_SUCCEEDED: 'ACCEPTVAKANSVAKTREQUEST_SUCCEEDED',
    ACCEPTVAKANSVAKTREQUEST_FAILED: 'ACCEPTVAKANSVAKTREQUEST_FAILED',

    START_UNDOVAKANSVAKTREQUEST: 'START_UNDOVAKANSVAKTREQUEST',
    UNDOVAKANSVAKTREQUEST_SUCCEEDED: 'UNDOVAKANSVAKTREQUEST_SUCCEEDED',
    UNDOVAKANSVAKTREQUEST_FAILED: 'UNDOVAKANSVAKTREQUEST_FAILED'
};
