export const tjenesteplanerConstants = {
    START_GET_TJENESTEPLANER: 'START_GET_TJENESTEPLANER',
    GET_TJENESTEPLANER_SUCCEEDED: 'GET_TJENESTEPLANER_SUCCEEDED',
    GET_TJENESTEPLANER_FAILED: 'GET_TJENESTEPLANER_FAILED',
    START_GET_TJENESTEPLAN: 'START_GET_TJENESTEPLAN',
    GET_TJENESTEPLAN_SUCCEEDED: 'GET_TJENESTEPLAN_SUCCEEDED',
    GET_TJENESTEPLAN_FAILED: 'GET_TJENESTEPLAN_FAILED',
    START_GET_WEEKLYTJENESTEPLAN: 'START_GET_WEEKLYTJENESTEPLAN',
    GET_WEEKLYTJENESTEPLAN_SUCCEEDED: 'GET_WEEKLYTJENESTEPLAN_SUCCEEDED',
    GET_WEEKLYTJENESTEPLAN_FAILED: 'GET_WEEKLYTJENESTEPLAN_FAILED',
    START_SAVE_TJENESTEPLAN: 'START_SAVE_TJENESTEPLAN',
    SAVE_TJENESTEPLAN_SUCCEEDED: 'SAVE_TJENESTEPLAN_SUCCEEDED',
    SAVE_TJENESTEPLAN_FAILED: 'SAVE_TJENESTEPLAN_FAILED',
    START_CHANGE_TJENESTEPLANLEGEDATE: 'START_CHANGE_TJENESTEPLANLEGEDATE',
    CHANGE_TJENESTEPLANLEGEDATE_SUCCEEDED: 'CHANGE_TJENESTEPLANLEGEDATE_SUCCEEDED',
    CHANGE_TJENESTEPLANLEGEDATE_FAILED: 'CHANGE_TJENESTEPLANLEGEDATE_FAILED'
};


export default tjenesteplanerConstants;