export const sykehusConstants = {
    START_GET_SYKEHUS: 'START_GET_SYKEHUS',
    GET_SYKEHUS_SUCCEEDED: 'GET_SYKEHUS_SUCCEEDED',
    GET_SYKEHUS_FAILED: 'GET_SYKEHUS_FAILED',

    START_CREATE_SYKEHUS: 'START_CREATE_SYKEHUS',
    CREATE_SYKEHUS_SUCCEEDED: 'CREATE_SYKEHUS_SUCCEEDED',
    CREATE_SYKEHUS_FAILED: 'CREATE_SYKEHUS_FAILED',

    START_EDIT_SYKEHUS: 'START_EDIT_SYKEHUS',
    EDIT_SYKEHUS_SUCCEEDED: 'EDIT_SYKEHUS_SUCCEEDED',
    EDIT_SYKEHUS_FAILED: 'EDIT_SYKEHUS_FAILED',

    START_DELETE_SYKEHUS: 'START_DELETE_SYKEHUS',
    DELETE_SYKEHUS_SUCCEEDED: 'DELETE_SYKEHUS_SUCCEEDED',
    DELETE_SYKEHUS_FAILED: 'DELETE_SYKEHUS_FAILED',
};


export default sykehusConstants;