export const minTjenesteplanConstants = {
    START_FETCH_MINTJENESTEPLAN: 'START_FETCH_MINTJENESTEPLAN',
    FETCH_MINTJENESTEPLAN_SUCCEEDED: 'FETCH_MINTJENESTEPLAN_SUCCEEDED',
    FETCH_MINTJENESTEPLAN_FAILED: 'FETCH_MINTJENESTEPLAN_FAILED',
    FETCH_MINTJENESTEPLAN_NOTFOUND: 'FETCH_MINTJENESTEPLAN_NOTFOUND',
    START_FETCH_MINETJENESTEPLANER: 'START_FETCH_MINETJENESTEPLANER',
    FETCH_MINETJENESTEPLANER_SUCCEEDED: 'FETCH_MINETJENESTEPLANER_SUCCEEDED',
    FETCH_MINETJENESTEPLANER_FAILED: 'FETCH_MINETJENESTEPLANER_FAILED'
};


export default minTjenesteplanConstants;