export const notificationsConstants = {
    START_GET_NOTIFICATIONS: 'START_GET_NOTIFICATIONS',
    GET_NOTIFICATIONS_SUCCEEDED: 'GET_NOTIFICATIONS_SUCCEEDED',
    GET_NOTIFICATIONS_FAILED: 'GET_NOTIFICATIONS_FAILED',
    START_SAVE_NOTIFICATIONREAD: 'START_SAVE_NOTIFICATIONREAD',
    SAVE_NOTIFICATIONREAD_SUCCEEDED: 'SAVE_NOTIFICATIONREAD_SUCCEEDED',
    SAVE_NOTIFICATIONREAD_FAILED: 'SAVE_NOTIFICATIONREAD_FAILED'
};


export default notificationsConstants;