export const userConstants = {
    START_REMOVEFROMAVDELING: 'START_REMOVEFROMAVDELING',
    REMOVEFROMAVDELING_SUCCEEDED: 'REMOVEFROMAVDELING_SUCCEEDED',
    REMOVEFROMAVDELING_FAILED: 'REMOVEFROMAVDELING_FAILED',

    START_ADDLEGETOAVDELING: 'START_ADDLEGETOAVDELING',
    ADDLEGETOVDELING_SUCCEEDED: 'ADDLEGETOVDELING_SUCCEEDED',
    AVDELING_FAILED: 'AVDELING_FAILED'
};


export default userConstants;